### PR TITLE
Image decoding, texture creation, tests and test textures, and a .gitignore!

### PR DESCRIPTION
**Pull request by zgoethel12**
A result of issue #1.  Overall a very productive session.  Let me know if any design choices were not in favor of the design of JGLOOm (e.g. in texture creation where I assumed `target` was `GL_TEXTURE_2D`, maybe I'll add a parameter).

### CODE REVIEW

**Comment by zgoethel12** [comment]
Any thoughts or ideas, @ecumene-software?

**Comment by ecumene-software** [comment]
Hey sorry I can't comment right now. I'll be out for fathers day until tomorrow aft. Have a good weekend!

**Comment by ecumene-software** [comment]
But I checked out the texture uploader, selecting the target would be nice. You may need a method for uploading to already made textures, then use that in your method to construct new textures.

Also you may want to move everything from src/test to src/tests ;)

**Comment by ecumene-software** [comment]
Last thing: Remove the `touch` files once the directory has files, then you don't need them.

**Comment by ecumene-software** [comment]
Also I really like ImageDataCallback! I'll stop spamming now, bedtime.

**Comment by zgoethel12** [comment]
Alright, sounds good.  I'll start working on those suggestions tomorrow afternoon!

**Comment by zgoethel12** [comment]
Also, learn about Gradle source folder naming conventions [here](https://docs.gradle.org/current/userguide/java_plugin.html#N152C8).

**Pull request merged**
